[workspace]
channels = [ "https://prefix.dev/pixi-build-backends", "conda-forge", "bioconda"]
platforms = ["linux-64"]
preview = ["pixi-build"]

[pypi-dependencies]
nanana = { path = ".", editable = true }

[tasks]

[package] 
name = "nanana"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "*" }

[package.host-dependencies] 
hatchling = "==1.26.3"

[environments]
prod = {features = [], solve-group = "default"}  # Default features is imply.
default =  {features = ["dev"], solve-group = "default" }

[dependencies]
python = ">=3.10.18,<=3.12"
hdbscan = ">=0.8.39,<0.9" # Clustering
matplotlib = ">=3.10.3,<4"
pandas = ">=2.3.0,<3"
pysam = ">=0.23.3,<0.24"
umap-learn = ">=0.5.7,<0.6"
taxonkit = ">=0.20.0,<0.21"
requests = ">=2.32.4,<3" # For database download
skani = ">=0.2.2,<0.3"   # polishing
canu = ">=2.3,<3"
racon = ">=1.5.0,<2"
edlib = ">=1.3.9,<2"
fastani = ">=1.34,<2"
biotite = ">=1.2.0,<2"
mappy = ">=2.30,<3"

[feature.dev.dependencies]
ipykernel = ">=6.30.1,<7"
ruff = ">=0.12.9,<0.13"
mypy = ">=1.17.1,<2"
